AllCops:
  TargetRubyVersion: 2.6

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/HashTransformValues:
  Enabled: false
